# Generated by Django 3.0.3 on 2020-04-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interior_design.Designer')),
            ],
        ),
    ]
