# Generated by Django 3.0.3 on 2020-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='signup',
            name='age',
            field=models.IntegerField(),
        ),
    ]
