# Generated by Django 3.0.3 on 2020-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_design', '0002_auto_20200318_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('Work_Experience', models.IntegerField()),
            ],
        ),
    ]
