# Generated by Django 3.0.3 on 2020-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_design', '0003_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='jornal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
